### PR TITLE
Add `to_dataframe` to `TTree`

### PR DESCRIPTION
**Pull request by tzuhanchang**
Add ```to_dataframe``` to ```TTree``` for converting TTree to a ```pandas.DataFrame```.

### CODE REVIEW

**Comment by jpivarski** [comment]
Hi! Thanks for your first pull request, but did you know that `library="pd"` can be passed to any array-fetching function (e.g. [uproot.TTree.arrays](https://uproot.readthedocs.io/en/latest/uproot.behaviors.TTree.TTree.html#arrays))? That does what this `to_dataframe` would do. (It's [here in the documentation](https://uproot.readthedocs.io/en/latest/basic.html#reading-a-tbranch-as-an-array).)

**Comment by tzuhanchang** [comment]
> Hi! Thanks for your first pull request, but did you know that `library="pd"` can be passed to any array-fetching function (e.g. [uproot.TTree.arrays](https://uproot.readthedocs.io/en/latest/uproot.behaviors.TTree.TTree.html#arrays))? That does what this `to_dataframe` would do. (It's [here in the documentation](https://uproot.readthedocs.io/en/latest/basic.html#reading-a-tbranch-as-an-array).)

Thank you very much. There are few challenges for using `library="pd"`. It does not play nice with "vector" leaf type, it creates subentry for an events, instead we want 1 event per row in the df. Also `tree.arrays(library="pd")` takes way too long to run when "vector" leaf type variables are present in the tree.

**Comment by jpivarski** [comment]
By "vector" leaf type, do you mean jagged arrays? A function that puts a list of numbers into a Pandas cell (as opposed to expanding that list into one number per cell, tracked by a MultiIndex) would have to have a name that clearly specifies that that's what it does.

I don't know of any Pandas functions that can deal adequately with non-numeric values in cells. It represents them as Python lists or NumPy arrays, and then you're forced to manipulate them with Python iteration, using one of the various `map` functions in Pandas. That doesn't scale to large datasets.

**Comment by tzuhanchang** [comment]
Thank you so much for your help!

**Pull request closed without merging**
