### PR TITLE
Pass exceptions to main thread in xrootd

### PR DESCRIPTION
**Pull request by btovar**
Sketch of a solution for issue #456. Simply catch the exception on the
callback and update the futures accordingly (as HTTP source does).

### CODE REVIEW

**Comment by btovar** [comment]
Sounds good @jpivarski, it looks good to me.

I agree with the difficulty of the testing.  I tried it here setting the timeouts to low values to trigger Operation Expired errors. The current pr does recover from those errors, but it was hard to reliably test it.

**Comment by jpivarski** [comment]
Okay, then I'll take it once pre-commit passes (https://results.pre-commit.ci/run/github/262422450/1634748035.QZ3W9c9lRrKb9ZLne5bcAQ). It's failing because you declared `e` (the exception object) and then didn't use it.

I'll turn on auto-merge, so that it merges once that's fixed.

**Comment by jpivarski** [comment]
@all-contributors please add @btovar for code

**Comment by btovar** [comment]
Great, thanks Jim.

**Pull request merged**
