### PR TITLE
Implement regular array support for TClonesArray

### PR DESCRIPTION
**Pull request by nsmith-**

### CODE REVIEW

**Comment by nsmith-** [comment]
The test will require merging https://github.com/scikit-hep/scikit-hep-testdata/pull/65

**Comment by nsmith-** [comment]
This will have issues with `delphes_tree["GenJet04/GenJet04.Constituents"].array(library="np")` once #441 is merged, need to look a bit more

**Comment by jpivarski** [comment]
> The test will require merging [scikit-hep/scikit-hep-testdata#65](https://github.com/scikit-hep/scikit-hep-testdata/pull/65)

See 

https://github.com/scikit-hep/scikit-hep-testdata/actions/runs/1247612638

to file the progress of releasing 0.4.8.

**Comment by jpivarski** [comment]
And ping me again when you're ready for this to be merged.

**Comment by lgray** [comment]
@jpivarski that CI run failed looking at the link!

**Comment by nsmith-** [comment]
Actually the problem was much more subtle: essentially by chance the data was such that numpy converted a list of `TRefArray`s with the same number of refs into a 2D array. This is because by default:
```python
>>> numpy.array([ [1,2], [3,4] ], dtype=object)
array([[1, 2],
       [3, 4]], dtype=object)
```

**Comment by nsmith-** [comment]
@jpivarski this is ready

**Pull request merged**
