### PR TITLE
Set up interface between Uproot and Awkward so that Awkward can be used to optimize object-reading.

### PR DESCRIPTION
**Pull request by jpivarski**
As discussed in issue #90.

Corresponds to scikit-hep/awkward-1.0#448.

### CODE REVIEW

**Comment by jpivarski** [comment]
@tamasgal The good news is that, with this PR and scikit-hep/awkward-1.0#448, the following code takes 3.6 seconds instead of 194 seconds (53× faster):

```python
import uproot4
branch = uproot4.open("issue-90.root:E/Evt/trks/trks.fitinf")
for i in range(branch.num_baskets):
    print(repr(branch.basket(i).array()))
```

In the above, we're reading each TBasket individually. The bad news is that it still takes a long time to concatenate TBaskets because [ak.concatenate](https://awkward-array.readthedocs.io/en/latest/_auto/ak.concatenate.html) has only been (internally) implemented for pairs: concatenating _n_ arrays means creating and throwing away _n - 2_ temporary arrays of quadratically increasing size. That was fine for examples of concatenating 2 or 3 arrays at a time, but when it comes to concatenating data from this file's 461 TBaskets, it's a problem.

Clearly, [ak.concatenate](https://awkward-array.readthedocs.io/en/latest/_auto/ak.concatenate.html) needs to be fixed anyway. There might already be an issue open about it. (It's been on my mind for a while...) Anyway, I'll tackle that next. We want the conclusion of the above story to be that the whole array is produced in 3.7 seconds!

**Comment by tamasgal** [comment]
Awesome! Many thanks, Jim, that's really a huge leap.

**Comment by jpivarski** [comment]
For cases that aren't covered by the new interpret-by-Awkward mechanism, how about parallelizing the pure Python interpretation?

   * **parallel interpretation in 'basket_array':** 259 seconds. 12 cores utilized at about 5-10% each. I'll blame the GIL. Reversing the order (putting the big TBaskets first) doesn't help—it's not about stragglers.
   * **sequential interpretation in 'basket_array', concatenate NumPy dtype=O arrays:** 190 seconds.
   * **sequential interpretation in 'final_array' (old way):** 197 seconds. Moving the interpretation from `final_array` into `basket_array` doesn't hurt. Entries that would be trimmed (because they're at the ends of the first and last basket) are now unnecessarily interpreted, but that's probably better than not having the possibility to parallelize.
   * **interpret-by-Awkward in 'basket_array':** 2.5 seconds.

So the baseline of 197 seconds wasn't unnecessarily harsh. It really is an 80× speedup.

**Comment by jpivarski** [comment]
Making use of this will require Awkward 0.2.37 (but it won't _break_ with earlier versions), which is being deployed now. I'll do one last test after that deployment so that GHA pulls the new Awkward from PyPI.

**Comment by tamasgal** [comment]
Thanks, that's really nice and helps a lot!

**Pull request merged**
