### PR TITLE
CI: rerun tests on network errors

### PR DESCRIPTION
**Pull request by veprbl**

### CODE REVIEW

**Comment by veprbl** [comment]
This should help with test failures like this one https://github.com/scikit-hep/uproot4/pull/407/checks?check_run_id=3363231826#step:9:360

**Comment by jpivarski** [comment]
Thanks! I didn't know about that.

**Comment by veprbl** [comment]
Strangely there are now some new failures for python3.5 in version solver of conda.

**Review by jpivarski — APPROVED** [review]
Let me know if you're done with this. I approve and will merge it when you give me the signal.

Thanks!

**Comment by veprbl** [comment]
I think this is good to go. I've restarted the jobs three times in my fork and didn't see any failures (although I did not see any HTTP errors). As usual, let me know if you encounter any problems with this one.

**Pull request merged**
