### PR TITLE
Re-enable Python 3.5 CI

### PR DESCRIPTION
**Pull request by chrisburr**
I'm making this PR to check if conda-forge was fixed correctly I don't mind if it's merged or just closed.

### CODE REVIEW

**Comment by jpivarski** [comment]
If it does work, I'll merge it!

**Comment by henryiii** [comment]
If we say we support 3.5, I want to have at least one ci job running 3.5 (same goes for 2.7, actually). (Though Linux only would be just fine). If we claim to support 3.5 but actually don't, that's _worse_ than just changing our minimum requires to remove 3.5, causing pip to pull old versions instead. This is exactly the same issue that pip's conda feedstock had, they didn't change what they claimed to support, so it broke!

**Comment by henryiii** [comment]
```
  OSError: XRootD error: [ERROR] Operation expired
E               in file root://eospublic.cern.ch//eos/root-eos/cms_opendata_2012_nanoaod/Run2012B_DoubleMuParked.root
```

**Comment by chrisburr** [comment]
I'll mark this as ready for review as the issue it's claiming to fix is sorted.

I've left a script running to see if I can get enough of a reproducer to open a ticket against EOS...

**Comment by chrisburr** [comment]
Ah I've finally figured it out, unauthenticated reads are _**often**_ failing but authenticated ones are _**always**_ fine.

I've opened a ticket: https://cern.service-now.com/service-portal?id=ticket&n=INC2684948

* With kerberos credentials:
```bash
$ ssh lxplus 'echo "Start" && time XRD_REQUESTTIMEOUT=20 xrdcp root://eospublic.cern.ch//eos/root-eos/cms_opendata_2012_nanoaod/Run2012B_DoubleMuParked.root - | head -c1000 > /dev/null'
Start
XRD_REQUESTTIMEOUT=20 xrdcp  -  0.01s user 0.03s system 39% cpu 0.106 total
head -c1000 > /dev/null  0.00s user 0.00s system 1% cpu 0.103 total
```

* Destroy kerberos credentials before reading:
```bash
$ ssh lxplus 'kdestroy && echo "Start" && time XRD_REQUESTTIMEOUT=20 xrdcp root://eospublic.cern.ch//eos/root-eos/cms_opendata_2012_nanoaod/Run2012B_DoubleMuParked.root - | head -c1000 > /dev/null'
Start
[0B/0B][100%][==================================================][0B/s]
Run: [ERROR] Operation expired:  (source)
XRD_REQUESTTIMEOUT=20 xrdcp  -  0.03s user 0.01s system 0% cpu 15.016 total
head -c1000 > /dev/null  0.00s user 0.00s system 0% cpu 15.016 total
```

**Comment by chrisburr** [comment]
@jpivarski The EOS issue is resolved now so this is ready to merge.

If anyone is interested there is a nice explanation about the root cause on the support ticket.

**Pull request merged**
